spring:
  application:
    name: helloservice
server:
  port: 5000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
    username: eurekaUser
    password: securePassword
  instance:
    hostname: localhost
    securePortEnabled: true
    nonSecurePortEnabled: false

security:
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: storepassword
    key-alias: selfsigned
    trust-store: classpath:truststore.jks
    trust-store-password: trustpassword