spring:
  application:
    name: helloservice
server:
  port: 5000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  instance:
    hostname: localhost